"""Text report templates."""

REPORT_HEADER = """MACHINE FAILURE INVESTIGATION
────────────────────────────────
"""

REPORT_FOOTER = """
────────────────────────────────
Generated by AI Machine Failure Investigator
This report is for research and demonstration purposes only.
"""
